### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by PetrSvirak** [skrovina/chat-m#1]
While there are 4 tests (in 3 test suites), you're missing all the other tests for your reducers, thunk actions, and utils functions.

To be able to write tests for the thunk actions properly, you'll need to inject their some of the functions they call in them. Use the factory pattern to achieve that. Something like this:

````
// actions/profile/fetchUserAvatar.js
export const fetchUserAvatarFactory = (dependencies) =>
  (avatarId) =>
    async (dispatch, getState) => {
      const avatarUri = await dependencies.fetchReceive(createApiFilerUri(avatarId));
      dispatch(updateProfileAvatar(avataruri));
    };
````
````
// actions/index.js
import { fetchUserAvatarFactory } from './profile/fetchUserAvatar';
import { fetchReceive } from '../../utils/api/fetchReceive';

export const fetchUserAvatar = fetchUserAvatarFactory({ fetchReceive });
````
````
// actions/profile/fetchUserAvatar.test.js
import { fetchUserAvatarFactory } from './fetchUserAvatar';

const fetchReceive = jest.fn(() => Promise.resolve());
const fetchUserAvatar = fetchUserAvatarFactory({ fetchReceive });
````

**Comment by skrovina** [comment]
In the epic test, I am mocking the httpRequest module, so there's no need for explicit injection.
There is one of a kind of every test (reducer, pure function, epic ~ thunk)
Is there any limit how many tests there should be?
I guess you're not expecting 100% test coverage.

**Comment by PetrSvirak** [comment]
Was sorted out via emails since I missed this comment. Now, the tests are good.
